name: Example workflow for Python using Snyk 
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        COMMAND: "pip install poetry && poetry config virtualenvs.create false && poetry install && pwd && ls"
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        
