
name: "Snyk"

# Run workflow each time code is pushed to your repository.
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          COMMAND: "pip install poetry && poetry install"
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    
