
name: "Snyk"

# Run workflow each time code is pushed to your repository.
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        continue-on-error: true       
        env:
           COMMAND: "pip install poetry && poetry install"
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    
