name: Example workflow for Python using Snyk 
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O snyk-jira-sync https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/download/0.7.0/snyk-jira-sync-linux
    - name: Jira Ticket Creation
      run:  snyk-jira-sync -orgID="${SNYK_ORG_ID}" -token="${SNYK_TOKEN}" -jiraProjectID="${JIRA_PROJECT_ID}" -severity=high
    
