name: Example workflow for Python using Snyk 
on: pull_request
jobs:
  security:
    runs-on: python:3.6
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        COMMAND: "pip install poetry && poetry install"
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=poetry.lock
